# Usa una imagen base de Python
FROM python:3.10-slim

# Instala las dependencias del sistema necesarias, incluidas las de CMake y dlib
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgtk2.0-dev \
    libgl1-mesa-glx \ 
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copia los archivos del proyecto
COPY . /app

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Exponemos el puerto (ajustarlo según la API)
EXPOSE 5000

# Comando para ejecutar el servidor de la API utilizando gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "face_recognition_knn:app"]